In [ ]:
https://raw.githubusercontent.com/PranavSagar/ML_dataset/main/Salaries.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#raw file link from github
url = 'https://raw.githubusercontent.com/PranavSagar/ML_dataset/main/Salaries.csv'

In [ ]:
#importing csv file
df = pd.read_csv(url)

In [ ]:
print(df.shape)
print(df.size)

(78, 6)
468


In [ ]:
print(df.info)

<bound method DataFrame.info of          rank discipline   phd  service     sex  salary
0        Prof          B  56.0     49.0    Male  186960
1        Prof          A  12.0      6.0    Male   93000
2        Prof          A  23.0     20.0    Male  110515
3        Prof          A  40.0     31.0    Male  131205
4        Prof          B  20.0     18.0    Male  104800
..        ...        ...   ...      ...     ...     ...
73       Prof          B  18.0     10.0  Female  105450
74  AssocProf          B  19.0      6.0  Female  104542
75       Prof          B  17.0     17.0  Female  124312
76       Prof          A  28.0     14.0  Female  109954
77       Prof          A  23.0     15.0  Female  109646

[78 rows x 6 columns]>


In [ ]:
x=df.iloc[:,:-1].values
print(x)

[['Prof' 'B' 56.0 49.0 'Male']
 ['Prof' 'A' 12.0 6.0 'Male']
 ['Prof' 'A' 23.0 20.0 'Male']
 ['Prof' 'A' 40.0 31.0 'Male']
 ['Prof' 'B' 20.0 18.0 'Male']
 ['Prof' 'A' 20.0 20.0 'Male']
 ['AssocProf' 'A' 20.0 17.0 'Male']
 ['Prof' 'A' 18.0 18.0 'Male']
 ['Prof' 'A' 29.0 19.0 'Male']
 ['Prof' 'A' 51.0 51.0 'Male']
 ['Prof' 'B' nan 33.0 'Male']
 ['Prof' 'B' 23.0 23.0 'Male']
 ['AsstProf' 'B' 1.0 0.0 'Male']
 ['Prof' 'B' 35.0 33.0 'Male']
 ['Prof' 'B' 25.0 19.0 'Male']
 ['Prof' 'B' 17.0 nan 'Male']
 ['AsstProf' 'B' 8.0 3.0 'Male']
 ['AsstProf' 'B' 4.0 0.0 nan]
 ['Prof' 'A' 19.0 7.0 'Male']
 ['Prof' 'A' nan 27.0 'Male']
 ['AsstProf' 'B' 4.0 4.0 'Male']
 ['Prof' nan 33.0 30.0 'Male']
 ['AsstProf' 'A' 4.0 2.0 'Male']
 ['AsstProf' 'A' 2.0 0.0 'Male']
 [nan 'A' 30.0 23.0 'Male']
 ['Prof' 'B' 35.0 31.0 'Male']
 ['Prof' 'A' 38.0 19.0 'Male']
 ['Prof' 'A' 45.0 43.0 'Male']
 ['AsstProf' nan 7.0 2.0 'Male']
 ['Prof' 'B' 21.0 20.0 'Male']
 ['AssocProf' 'B' 9.0 7.0 'Male']
 ['Prof' 'B' 22.0 21.0 'Male

In [ ]:
y=df.iloc[:,5].values
print(y)

[186960  93000 110515 131205 104800 122400  81285 126300  94350  57800
 128250 134778  88000 162200 153750 150480  75044  92000 107300 150500
  92000 103106  73000  85000  91100  99418 148750 155865  91300 123683
 107008 155750 103275 120000 119800 126933 146856 102000  91000 129000
 137000  74830  80225  77000 151768 140096  74692 103613 111512 122960
  97032 127512 105000  73500  62884  72500  77500  72500 144651 103994
  92000 103750 109650  91000  73300 117555  63100  90450  77500 116450
  78500  71065 161101 105450 104542 124312 109954 109646]


In [ ]:
class_count=df.groupby('sex').size()
print(class_count)

sex
Female    39
Male      38
dtype: int64


In [ ]:
correlation=df.corr(method='pearson')
print(correlation)

              phd   service    salary
phd      1.000000  0.928182  0.573382
service  0.928182  1.000000  0.563814
salary   0.573382  0.563814  1.000000


In [ ]:
df.describe()


phd    service         salary
count  76.000000  77.000000      78.000000
mean   19.328947  15.207792  108023.782051
std    12.414388  12.139906   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.000000   6.000000   88612.500000
50%    18.000000  15.000000  104671.000000
75%    26.250000  21.000000  126774.750000
max    56.000000  51.000000  186960.000000

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean',fill_value=None,verbose=0)

In [ ]:
imputer=imputer.fit(x[:,2:4])

In [ ]:
x[:,2:4]=imputer.transform(x[:,2:4])

In [ ]:
print(x)

[['Prof' 'B' 56.0 49.0 'Male']
 ['Prof' 'A' 12.0 6.0 'Male']
 ['Prof' 'A' 23.0 20.0 'Male']
 ['Prof' 'A' 40.0 31.0 'Male']
 ['Prof' 'B' 20.0 18.0 'Male']
 ['Prof' 'A' 20.0 20.0 'Male']
 ['AssocProf' 'A' 20.0 17.0 'Male']
 ['Prof' 'A' 18.0 18.0 'Male']
 ['Prof' 'A' 29.0 19.0 'Male']
 ['Prof' 'A' 51.0 51.0 'Male']
 ['Prof' 'B' 19.32894736842105 33.0 'Male']
 ['Prof' 'B' 23.0 23.0 'Male']
 ['AsstProf' 'B' 1.0 0.0 'Male']
 ['Prof' 'B' 35.0 33.0 'Male']
 ['Prof' 'B' 25.0 19.0 'Male']
 ['Prof' 'B' 17.0 15.207792207792208 'Male']
 ['AsstProf' 'B' 8.0 3.0 'Male']
 ['AsstProf' 'B' 4.0 0.0 nan]
 ['Prof' 'A' 19.0 7.0 'Male']
 ['Prof' 'A' 19.32894736842105 27.0 'Male']
 ['AsstProf' 'B' 4.0 4.0 'Male']
 ['Prof' nan 33.0 30.0 'Male']
 ['AsstProf' 'A' 4.0 2.0 'Male']
 ['AsstProf' 'A' 2.0 0.0 'Male']
 ['0' 'A' 30.0 23.0 'Male']
 ['Prof' 'B' 35.0 31.0 'Male']
 ['Prof' 'A' 38.0 19.0 'Male']
 ['Prof' 'A' 45.0 43.0 'Male']
 ['AsstProf' nan 7.0 2.0 'Male']
 ['Prof' 'B' 21.0 20.0 'Male']
 ['AssocProf' 'B' 9

In [ ]:
imputer2=SimpleImputer(missing_values=np.nan,strategy='constant',fill_value='0',verbose=0)

In [ ]:
imputer2=imputer2.fit(x[:,0:2])

In [ ]:
x[:,0:2]=imputer2.transform(x[:,0:2])

In [ ]:
print(x)

[['Prof' 'B' 56.0 49.0 'Male']
 ['Prof' 'A' 12.0 6.0 'Male']
 ['Prof' 'A' 23.0 20.0 'Male']
 ['Prof' 'A' 40.0 31.0 'Male']
 ['Prof' 'B' 20.0 18.0 'Male']
 ['Prof' 'A' 20.0 20.0 'Male']
 ['AssocProf' 'A' 20.0 17.0 'Male']
 ['Prof' 'A' 18.0 18.0 'Male']
 ['Prof' 'A' 29.0 19.0 'Male']
 ['Prof' 'A' 51.0 51.0 'Male']
 ['Prof' 'B' 19.32894736842105 33.0 'Male']
 ['Prof' 'B' 23.0 23.0 'Male']
 ['AsstProf' 'B' 1.0 0.0 'Male']
 ['Prof' 'B' 35.0 33.0 'Male']
 ['Prof' 'B' 25.0 19.0 'Male']
 ['Prof' 'B' 17.0 15.207792207792208 'Male']
 ['AsstProf' 'B' 8.0 3.0 'Male']
 ['AsstProf' 'B' 4.0 0.0 nan]
 ['Prof' 'A' 19.0 7.0 'Male']
 ['Prof' 'A' 19.32894736842105 27.0 'Male']
 ['AsstProf' 'B' 4.0 4.0 'Male']
 ['Prof' '0' 33.0 30.0 'Male']
 ['AsstProf' 'A' 4.0 2.0 'Male']
 ['AsstProf' 'A' 2.0 0.0 'Male']
 ['0' 'A' 30.0 23.0 'Male']
 ['Prof' 'B' 35.0 31.0 'Male']
 ['Prof' 'A' 38.0 19.0 'Male']
 ['Prof' 'A' 45.0 43.0 'Male']
 ['AsstProf' '0' 7.0 2.0 'Male']
 ['Prof' 'B' 21.0 20.0 'Male']
 ['AssocProf' 'B' 9

In [ ]:
imputer3=SimpleImputer(missing_values=np.nan,strategy='constant',fill_value='0',verbose=0)
imputer2=imputer2.fit(x[:,4:5])
x[:,4:5]=imputer2.transform(x[:,4:5])
print(x)

[['Male' 'Male' 56.0 49.0 'Male']
 ['Male' 'Male' 12.0 6.0 'Male']
 ['Male' 'Male' 23.0 20.0 'Male']
 ['Male' 'Male' 40.0 31.0 'Male']
 ['Male' 'Male' 20.0 18.0 'Male']
 ['Male' 'Male' 20.0 20.0 'Male']
 ['Male' 'Male' 20.0 17.0 'Male']
 ['Male' 'Male' 18.0 18.0 'Male']
 ['Male' 'Male' 29.0 19.0 'Male']
 ['Male' 'Male' 51.0 51.0 'Male']
 ['Male' 'Male' 19.32894736842105 33.0 'Male']
 ['Male' 'Male' 23.0 23.0 'Male']
 ['Male' 'Male' 1.0 0.0 'Male']
 ['Male' 'Male' 35.0 33.0 'Male']
 ['Male' 'Male' 25.0 19.0 'Male']
 ['Male' 'Male' 17.0 15.207792207792208 'Male']
 ['Male' 'Male' 8.0 3.0 'Male']
 ['0' '0' 4.0 0.0 '0']
 ['Male' 'Male' 19.0 7.0 'Male']
 ['Male' 'Male' 19.32894736842105 27.0 'Male']
 ['Male' 'Male' 4.0 4.0 'Male']
 ['Male' 'Male' 33.0 30.0 'Male']
 ['Male' 'Male' 4.0 2.0 'Male']
 ['Male' 'Male' 2.0 0.0 'Male']
 ['Male' 'Male' 30.0 23.0 'Male']
 ['Male' 'Male' 35.0 31.0 'Male']
 ['Male' 'Male' 38.0 19.0 'Male']
 ['Male' 'Male' 45.0 43.0 'Male']
 ['Male' 'Male' 7.0 2.0 'Male']

In [ ]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
one_hotencoder=preprocessing.OneHotEncoder(sparse=False)
x=one_hotencoder.fit_transform(x) 
print(x)

[[0. 0. 1. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]]
